logging.level:
  garbagetown: DEBUG
  org.terasoluna: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/tourreserve
    username: postgres
    password: P0stgres

  thymeleaf.cache: false

security.basic.enabled: false

customer:
  initialBirthYear: 1980
  initialBirthMonth: 1
  initialBirthDay: 1
